spring.application.name=User Management
server.port=7081

spring.data.mongodb.uri=mongodb+srv://STM_Mongo_User:RBmrugRNpkSKvrMR@stm-cluster.authwif.mongodb.net/?appName=STM-Cluster
spring.data.mongodb.database=user_db

#Eureka Configuration
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:7111/eureka/
eureka.instance.hostname=localhost
eureka.instance.virtual-host-name=USER-SVC

#Logging config
logging.level.root=INFO
logging.level.com.taskmanager=DEBUG
logging.level.org.springframework.web=WARN

#Swagger Config
com.taskmanager.swagger.autoconfig = true


#JWT Secret Key
jwt.secretkey =7f8e2b1c4d5a6e7f8e2b1c4d5a6e7f8e2b1c4d5a6e7f8e2b1c4d5a6e7f8e2b1c
jwt.refresh.expiration = 900
jwt.access.expiration = 300